[package]
name = "faris-bot"
version = "0.1.0"
authors = [
    "Julian Gu <j.gush99@gmail.com>"
]
edition = "2018"

[dependencies]
env_logger = "0.6"
kankyo = "0.2"
log = "0.4"
serenity = "0.8"
rand="0.7.3"
chrono="0.4.0"
